// Each pair has two similar-but-different words.
// The first word goes to Civilians, the second to Undercovers (randomized at game start).
export const wordPairs: [string, string][] = [
  ["Cat", "Dog"],
  ["Coffee", "Tea"],
  ["Guitar", "Violin"],
  ["Beach", "Pool"],
  ["Pizza", "Burger"],
  ["Rain", "Snow"],
  ["Bicycle", "Motorcycle"],
  ["Notebook", "Diary"],
  ["Sofa", "Armchair"],
  ["Pancake", "Waffle"],
  ["Socks", "Stockings"],
  ["Lipstick", "Lip gloss"],
  ["Microwave", "Oven"],
  ["Pillow", "Cushion"],
  ["Shampoo", "Conditioner"],
  ["Sunrise", "Sunset"],
  ["Butter", "Margarine"],
  ["Frog", "Toad"],
  ["Dolphin", "Whale"],
  ["Gloves", "Mittens"],
  ["Ketchup", "Mustard"],
  ["Stairs", "Escalator"],
  ["Candle", "Lamp"],
  ["Museum", "Gallery"],
  ["Taxi", "Uber"],
  ["Yoga", "Pilates"],
  ["Soup", "Stew"],
  ["Boots", "Sneakers"],
  ["Curtains", "Blinds"],
  ["Lemon", "Lime"],
  ["Necklace", "Bracelet"],
  ["Croissant", "Muffin"],
  ["Tent", "Cabin"],
  ["Lake", "Pond"],
  ["Chocolate", "Caramel"],
  ["Volcano", "Mountain"],
  ["Sword", "Knife"],
  ["Castle", "Palace"],
  ["Pirate", "Ninja"],
  ["Dentist", "Doctor"],
  ["Mars", "Moon"],
  ["Skateboard", "Scooter"],
  ["Parrot", "Parakeet"],
  ["Couch", "Bed"],
  ["Bowling", "Golf"],
  ["Wallet", "Purse"],
  ["Jam", "Jelly"],
  ["Tornado", "Hurricane"],
  ["Cello", "Bass"],
  ["Igloo", "Tent"],
];
