// Each pair has two clearly different things in the same category.
// They're distinct enough that players know which they have,
// but close enough that vague clues could apply to either.
export const wordPairs: [string, string][] = [
  ["Cat", "Dog"],
  ["Coffee", "Tea"],
  ["Dolphin", "Whale"],
  ["Guitar", "Piano"],
  ["Beach", "Pool"],
  ["Pizza", "Burger"],
  ["Rain", "Snow"],
  ["Bicycle", "Car"],
  ["Sun", "Moon"],
  ["Pencil", "Pen"],
  ["Airplane", "Helicopter"],
  ["Soccer", "Basketball"],
  ["Bread", "Rice"],
  ["Shirt", "Jacket"],
  ["River", "Ocean"],
  ["Camping", "Hotel"],
  ["Candle", "Flashlight"],
  ["Subway", "Bus"],
  ["Apple", "Banana"],
  ["Chair", "Bed"],
  ["Dentist", "Barber"],
  ["Movie", "Concert"],
  ["Painting", "Photograph"],
  ["Snowboard", "Surfboard"],
  ["Glasses", "Contacts"],
  ["Elevator", "Stairs"],
  ["Newspaper", "Magazine"],
  ["Breakfast", "Dinner"],
  ["Forest", "Desert"],
  ["Cow", "Horse"],
  ["Violin", "Trumpet"],
  ["Sushi", "Tacos"],
  ["Castle", "Skyscraper"],
  ["Pirate", "Cowboy"],
  ["Tent", "Cabin"],
  ["Skateboard", "Rollerblades"],
  ["Volcano", "Earthquake"],
  ["Astronaut", "Pilot"],
  ["Library", "Bookstore"],
  ["Chocolate", "Ice Cream"],
  ["Penguin", "Parrot"],
  ["Sword", "Bow"],
  ["Fireworks", "Lightning"],
  ["Bathtub", "Shower"],
  ["Gloves", "Scarf"],
  ["Microphone", "Speaker"],
  ["Wallet", "Backpack"],
  ["Tiger", "Lion"],
  ["Cake", "Cookie"],
  ["Hammock", "Swing"],
];
